routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware('auth')->group(function(){
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout');
Route::resource('categories', 'CategoryController');
Route::resource('posts', 'PostController');
Route::resource('tags', 'TagController');
Route::get('trashed-post','PostController@trashed')->name('trashed-posts.index');
Route::put('restore-post/{post}', 'PostController@restore')->name('restore-posts');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Post;

class Tag extends Model
{
    protected $fillable =[
        'name'
    ];

    public function posts(){
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tag;
use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         
        return view('tags.index')->with('tags', Tag::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    //CreateTagRequest menginjek suatu kategori request sebelumnya ini pake request friss
    public function store(CreateTagRequest $request)
    {
      
        Tag::create([
            'name' => $request['name']
        ]);
        session()->flash('success','Tag Created Succesfully');
        return redirect(route('tags.index'));
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {   
        
        return view('tags.create')->with('tag', $tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        //
        $tag['name'] = $request['name'];
        $tag->save();
        session()->flash('success','Tag Updated Succesfully');
        return redirect('tags');   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        if($tag->posts->count() > 0){
            session()->flash('error', 'Tag can not be deleted because it has post/s');
            return redirect()->back();
        }else{
            $tag->delete();
        }
        session()->flash('success','Tag deleted Successfully');
        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')
@section('content')
 <div class="card card-default">
    <div class="card-header">
        {{ isset($tag) ? 'Edit tag':'Create tag' }}
    </div>
    <div class="card-body">
    @include('partial.errors')
  
    <form action="{{ isset($tag) ? route( 'tags.update',$tag->id) : route( 'tags.store') }}" method="POST">
    @csrf
    <!- Tell the laravel to choose which one is used method-->
    @if(isset($tag))
        @method('PUT')
    @endif
        <div class="form-group">
            <input type="text" class="form-control" name="name" placeholder="Tag Name"
            value=" {{ isset($tag) ? $tag->name:' ' }} ">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">{{isset($tag) ? 'Edit categorie' : 
            'Add Tag'}}</a>
        </div>
    </form>
    </div>
 </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="d-flex justify-content-end">
    <a href="{{ route('tags.create')}}" class="btn btn-success my-2">Add Tag</a>
    </div>
     <div class="card-default">
        <div class="card-header">
            Tags
        </div>
        <div class="card-body">
        @if($tags->count() > 0)
        <table class="table">
            <thead>
                <th>Name</th>
                <th>Post Count</th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
                @foreach($tags as $tag)
                    <tr>
                        <td>{{ $tag->name }}</td>
                        <td>{{ $tag->posts->count() }}</td>
                        <td><a class="btn btn-danger my-2" onclick="handleDelete({{$tag->id}})">Delete</button></a>
                        <td><a class="btn btn-info my-2" href="{{ route('tags.edit',$tag->id) }}">Update</button></a>
                    </tr>
                @endforeach
            </tbody>
            </table> 
        @else
        <h4 class="text-center">No Tag Yet</h4>
        @endif
           <form action="" id="deleteTagForm" method="POST"> 
           @csrf
           @method('DELETE')
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Tag</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure want to delete this Tag?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Go back</button>
                        <button type="submit" class="btn btn-primary">Yes, Delete</button>
                    </di/v>
                    </div>
                </div>
                </div>
           </form>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
    function handleDelete(id)
    {
        var form = document.getElementById('deleteTagForm')        
        form.action = '/tags/'+id
        console.log(form)
        $('#deleteModal').modal('show')
    }
    </script>
@endsection