routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware('auth')->group(function(){
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout');
Route::resource('categories', 'CategoryController');
Route::resource('posts', 'PostController');
Route::resource('tags', 'TagController');
Route::get('trashed-post','PostController@trashed')->name('trashed-posts.index');
Route::put('restore-post/{post}', 'PostController@restore')->name('restore-posts');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage; 
use App\Category;
use App\Tag ;


class Post extends Model
{   
    use SoftDeletes;
    protected $fillable =[
        'title',
        'description',
        'content',
        'image',
        'published_at',
        'category_id'
    ];
    /**
     * Delete post
     * @return void 
     */

    public function deleteImage(){
        Storage::delete($this->image);
    }
    public function category(){
        return $this->belongsTo(Category::class);
    }
    public function tags(){
        return $this->belongsToMany(Tag::class);
    }
    /**
     * mengembalikan id tag yang dimiliki oleh post. Hasil pemrosesan saat create adalah
     * array dalam array jadi arraynya itu cuman diambil idnya(casenya elemen arraynya banyak)
     * 
     * @return bool
     */
    public function hasTag($TagId){
        return in_array($TagId, $this->tags->pluck('id')->toArray());
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Http\Requests\postss\CreatePostsRequest;
use App\Http\Requests\postss\UpdatePostRequest;
use App\Category;
use App\Tag;


class PostController extends Controller
{
    public function __construct(){
        
        $this->middleware('verifyCategoriesCount')->only(['create','store']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        return view('posts.index') -> with('posts', Post::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('posts.create')->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostsRequest $request)
    { 
        $image = $request->image->store('posts');

        $post =Post::create([
            'title'=>$request['title'],
            'description' => $request['description'],
            'content' => $request['content'],
            'image' =>$image,
            'published_at' => $request['published_at'],
            'category_id'=>$request['category']
        ]);

        if($request->tags){
            $post->tags()->attach($request->tags);
        }
        session()->flash('success', 'Post created successfully');
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
       return view('posts.create')->with('post', $post)->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $data = $request->only(['title','content','description','published_at']);

        if($request->hasFile('image')){

            $image = $request->image->store('posts'); 
            
            $post->deleteImage();
            
            $data['image'] =$image;
        }

        $post->update($data);
        
        /**
         * sync() untuk menyinkronkan updateny kalo belum tag yang dipilih
         * sebelumnya belum diattach maka jadi diattach begitu juga sebaliknya
         */
        if($request->tags){
            $post->tags()->sync($request->tags);
        }
        session()->flash('success', 'Post updated successfully');
        
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      
        $post = Post::withTrashed()->where('id',$id)->firstOrFail();

        if($post->trashed()){
           
            $post->deleteImage();
           
            $post->forceDelete();
        
        }else{

            $post->delete();//softDelete
        }
        session()->flash('success', 'Post deleted successfully');
        return redirect(route('posts.index'));
 
    }
    /**
     * Show all the list of trased posts
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function trashed(){
          /**
         * withTrashed return all record trashed or not
         * onlyTrashed return all trashed record
         */

        $trashed = Post::onlyTrashed()->get();        
        return view('posts.index')->with('posts',$trashed);
        //return view('posts.index')->with('posts',$trashed);
    }
    public function restore($id){
         
        $post = Post::withTrashed()->where('id',$id)->firstOrFail();
        $post->restore();
        session()->flash('success', 'Post restored successfully');
        return redirect()->back();
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('content')
<div class="card card-default">

    <div class="card-header">
        Create Post
    </div>
    <div class="card-body">
    @include('partial.errors')
    <form action="{{ isset($post) ? route('posts.update',$post->id):route('posts.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    @if(isset($post))
    @method('PUT')
    @endif
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" name="title" id="title" value="{{ isset($post) ? $post->title : '' }}">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea name="description"  class="form-control" id="description" cols="30" rows="5">
            {{ isset($post) ? $post->description:'' }}
            </textarea>
        </div>
        <div class="form-group">
            <label for="content">Content</label> 
            <input id="content" type="hidden" name="content" value="{{ isset($post) ? $post->content:'' }}">
            <trix-editor input="content"></trix-editor>
        </div>
        <div class="form-group">
            <label for="publised_at">Published at</label>
            <input type="text" class="form-control" name="published_at" id="published_at" value="{{ isset($post) ? $post->published_at:'' }}">
        </div>
        @if(isset($post))
        <div class="form-group"> 
            <img src="/storage/{{$post->image}}" style="width:100%">
         </div>
        @endif 
        <div class="form-group">
            <label for="image">Image</label>
            <input type="file" class="form-control" name="image" id="image" sty >
        </div> 
        <div class="form-group">
            <label for="category">Category</label>
            <select name="category" id="category" class="form-control">
            @foreach($categories as $category)
            <option value="{{ $category->id }}"
                @if(isset($post))
                    @if($category->id == $post->category_id)
                    selected
                    @endif
                @endif

            >{{$category->name}}</option>
            @endforeach
            </select>
        </div>
        
        @if($tags->count() > 0)
        <div class="form-group">
            <label for="tags">Tag</label>
                <select name="tags[]" id="tags" class="form-control tags-selector" multiple>
                    @foreach ($tags as $tag)
                        <option value=" {{ $tag->id }} "
                            @if(isset($post))
                                @if ($post->hasTag($tag->id))
                                    selected
                            @endif
                            @endif
                        >{{ $tag->name }}</option>
                    @endforeach
                </select>
        </div>
        @endif
        
        <div class="form-group">
            <button type ="submit" class="btn btn-success" class="form-control">
                {{isset($post)?'Update Post':'Create Post'}}
            </button>
        </div>
    </form>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
<script>
    flatpickr('#published_at',{
        enableTime : true
    })
    $(document).ready(function(){
        $('.tags-selector').select2();
    })
</script>
@endsection
@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-end">
        <a href=" {{ route('posts.create') }} " class="btn btn-success form-group">Add Post</a>
</div>
<div class="card-default">
        <div class="card-header">Post</div>
        <div class="card-body">
        @if($posts->count() > 0)
                <table class="table">
                        <thead>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Category</th>
                        <th>Action</th>
                        <th></th>
                        </thead>       
                <tbody>
                @foreach ($posts as $post)
                <tr>
                        <td> <img src="/storage/{{$post->image}}" width="120px" height="60px"> </td>  
                        <td>{{ $post->title}}</td>
                        <td><a href=" {{ route('categories.edit', $post->category->id)}} "> {{ $post->category->name}}</a></td>
                @if($post->trashed())
                <td>
                <form action=" {{ route('restore-posts',$post->id)}} " method="POST"> 
                        @csrf
                        @method('PUT')
                        <button type="submit" class="btn btn-info btn-sm">Restore</button> 
               </form>
                </td>
                @else                
                <td> <a href=" {{ route('posts.edit',$post->id)}}" class="btn btn-info btn-sm">Edit</a></td>
                @endif
                <td>
                <form action="{{route('posts.destroy', $post->id)}}" method="POST">
                @csrf
                @method('DELETE')
                        <button type="submit" class="btn btn-danger btn-sm">
                        {{$post->trashed()?'Delete':'Trash'}}
                        </button>
                </form>
                </td>
                </tr>
                @endforeach
                </tbody>
                </table>
        @else
                <h4 class="text-center">No Post Yet</h4>
        @endif
        </div>
</div>
@endsection