routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware('auth')->group(function(){
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout');
Route::resource('categories', 'CategoryController');
Route::resource('posts', 'PostController');
Route::resource('tags', 'TagController');
Route::get('trashed-post','PostController@trashed')->name('trashed-posts.index');
Route::put('restore-post/{post}', 'PostController@restore')->name('restore-posts');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Post;

class Category extends Model
{
    protected $fillable = ['name'];
    /**
     * Category has many post
     */
    public function posts(){
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoryRequest;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        return view('categories.index')->with('categories', Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    //CreateCategoryRequest menginjek suatu kategori request sebelumnya ini pake request friss
    public function store(CreateCategoryRequest $request)
    {
      
        Category::create([
            'name' => $request['name']
        ]);
        session()->flash('success','Category Created Succesfully');
        return redirect(route('categories.index'));
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories.create')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        //
        $category['name'] = $request['name'];
        $category->save();
        session()->flash('success','Category Updated Succesfully');
        return redirect('categories');   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        
        if($category->posts->count() > 0){
            session()->flash('error', 'Category can be deleted because it has post');
            return redirect()->back();
        }else{
            $category->delete();
        }
        session()->flash('success','Category deleted Successfully');
        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')
@section('content')
 <div class="card card-default">
    <div class="card-header">
        {{ isset($category) ? 'Edit Category':'Create Category' }}
    </div>
    <div class="card-body">
    @include('partial.errors')
    <form action="{{ isset($category) ? route( 'categories.update',$category->id) : route( 'categories.store') }}" method="POST">
    @csrf
    <!- Tell the laravel to choose which one is used method-->
    @if(isset($category))
        @method('PUT')
    @endif
        <div class="form-group">
            <input type="text" class="form-control" name="name" placeholder="Category Name"
            value="{{ isset($category) ? $category->name : ' '}}">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">{{isset($category) ? 'Edit categorie' : 
            'Add categorie'}}</a>
        </div>
    </form>
    </div>
 </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="d-flex justify-content-end">
    <a href="{{ route('categories.create')}}" class="btn btn-success my-2">Add Category</a>
    </div>
     <div class="card-default">
        <div class="card-header">
            Categories
        </div>
        <div class="card-body">
        @if($categories->count() > 0)
        <table class="table">
            <thead>
                <th>Name</th>
                <th>Post Count</th>
                <th></th>
            </thead>
            <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td>{{ $category->name }}</td>
                        <td>{{ $category->posts->count()}}</td>
                        <td><a class="btn btn-danger my-2" onclick="handleDelete({{$category->id}})">Delete</button></a>
                        <td><a class="btn btn-info my-2" href="{{ route('categories.edit',$category->id) }}">Update</button></a>
                    </tr>
                @endforeach
            </tbody>
            </table> 
        @else
        <h4 class="text-center">No Category Yet</h4>
        @endif
           <form action="" id="deleteCategoryForm" method="POST"> 
           @csrf
           @method('DELETE')
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Category</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure want to delete this category?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Go back</button>
                        <button type="submit" class="btn btn-primary">Yes, Delete</button>
                    </di/v>
                    </div>
                </div>
                </div>
           </form>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
    function handleDelete(id)
    {
        var form = document.getElementById('deleteCategoryForm')        
        form.action = '/categories/'+id
        console.log(form)
        $('#deleteModal').modal('show')
    }
    </script>
@endsection

resources/views/categories/update.blade.php
@extends('layouts.app')
@section('content')
 <div class="card card-default">
    <div class="card-header">
        Add Category
    </div>
    <div class="card-body">
    @if($errors->any())
    <div class="alert alert-danger">
        <ul class="list-group">
            @foreach($errors->all() as $error)
                <li class="list-group-item text-danger">
                {{$error}}
                </li>
            @endforeach
        </ul>
    </div>
    @endif
    <form action="{{ route( 'categories.update', $category->id) }}" method="PUT">
    @csrf
        <div class="form-group">
            <input type="text" class="form-control" name="name" placeholder="Category Name" value={{$category->name}}>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Add categorie</a>
        </div>
    </form>
    </div>
 </div>
@endsection